exclude: [reference]

title: Rasmus Israelsson

permalink: /:categories/:year/:month/:day/:title/

# Build settings
markdown: redcarpet
redcarpet:   
  extensions: ["strikethrough","fenced_code_blocks"] 